---
  - name: Retrieve OpenShift credentials
    include_vars: "{{ role_path }}/defaults/openshift_credentials.yml"

  - name: Log in (obtain access token)
    redhat.openshift.openshift_auth:
      username: "{{ role_upgrade_check_openshift_username }}"
      password: "{{ role_upgrade_check_openshift_password }}"
    register: openshift_auth_results
