---
- name: Retrieve the prometheus-k8s route from the openshift-monitoring namespace
  kubernetes.core.k8s_info:
    api_key: "{{ openshift_auth_results.openshift_auth.api_key }}"
    kind: Route
    name: prometheus-k8s
    namespace: openshift-monitoring
  register: monitoring_routes
  no_log: True
 
- name: Set the prometheus URL
  set_fact:
    role_prometheus_url: "{{ monitoring_routes.resources | json_query('[].spec.host') }}"
  no_log: True

- name: Verify Node Memory Consumption
  block:
  - name: Retrieve Node CPU utilization
    uri:
      url:  "https://{{ role_prometheus_url[0] }}/api/v1/query?query=instance:node_cpu_utilisation:rate1m*100" 
      method: GET
      headers:
        Content-Type: application/json
        Accept: application/json
        Authorization: "Bearer {{ openshift_auth_results.openshift_auth.api_key }}"
      validate_certs: no
    register: payload_loadcpu
    no_log: True
  
  - name: Format cpu usage data
    set_fact:
      node_list_cpu: "{{ node_list_cpu | default([]) + [[item | json_query('value[1]'), item | json_query('metric.instance')]] }}"
    loop: "{{ payload_loadcpu.json.data.result }}"
    no_log: True
  
  - name: Assert cpu usage is below defined percentage
    assert:
      that: "{{ item[0] | int < openshift_upgrade_checks_cpu_threshold_percentage }}"
      quiet: yes
    loop: "{{ node_list_cpu }}"
    loop_control:
      label: "{{ item[1] }} < {{ openshift_upgrade_checks_cpu_threshold_percentage }}%"

- name: Verify Node Memory Consumption
  block:
  - name: Retrieve Node Memory utilization
    uri:
      url:  "https://{{ role_prometheus_url[0] }}/api/v1/query?query=instance:node_memory_utilisation:ratio*100" 
      method: GET
      headers:
        Content-Type: application/json
        Accept: application/json
        Authorization: "Bearer {{ openshift_auth_results.openshift_auth.api_key }}"
      validate_certs: no
    register: payload_loadmem
    no_log: True

  - name: Format memory usage data 
    set_fact:
      node_list_mem: "{{ node_list_mem | default([]) + [[item | json_query('value[1]'), item | json_query('metric.instance')]] }}"
    loop: "{{ payload_loadmem.json.data.result }}"
    no_log: True
  
  - name: Assert memory usage is below defined percentage
    assert:
      that: "{{ item[0] | int < openshift_upgrade_checks_memory_threshold_percentage }}"
      quiet: yes
    loop: "{{ node_list_mem }}"
    loop_control:
      label: "{{ item[1] }} < {{ openshift_upgrade_checks_memory_threshold_percentage }}%"

- name: Verify Node Disk Consumption
  block:
  - name: Retrieve Node Disk utilization
    uri:
      url:  "https://{{ role_prometheus_url[0] }}/api/v1/query?query=instance_device:node_disk_io_time_seconds:rate1m*100"
      method: GET
      headers:
        Content-Type: application/json
        Accept: application/json
        Authorization: "Bearer {{ openshift_auth_results.openshift_auth.api_key }}"
      validate_certs: no
    register: payload_loaddisk
    no_log: True
  
  - name: Format disk usage data 
    set_fact:
      node_list_disk: "{{ node_list_disk | default([]) + [[item | json_query('value[1]'), item | json_query('metric.instance')]] }}"
    loop: "{{ payload_loaddisk.json.data.result }}"
    no_log: True
  
  - name: Assert disk usage is below defined percentage
    assert:
      that: "{{ item[0] | int < openshift_upgrade_checks_disk_threshold_percentage }}"
      quiet: yes
    loop: "{{ node_list_disk }}"
    loop_control:
      label: "{{ item[1] }} < {{ openshift_upgrade_checks_disk_threshold_percentage }}%"


- name: Verify that requests are not taking a too much part of node cpus
  block:
  - name: Retrieve requests against CPU
    uri:
      url:  "https://{{ role_prometheus_url[0] }}/api/v1/query?query={{ openshift_upgrade_checks_requests_overall_cpu_query | urlencode }}"
      method: GET
      headers:
        Content-Type: application/json
        Accept: application/json
        Authorization: "Bearer {{ openshift_auth_results.openshift_auth.api_key }}"
      validate_certs: no
    register: payload_requestscpu

  - name: Format request_cpu usage data
    set_fact:
      request_cpu_list: "{{ request_cpu_list | default([]) + [[item | json_query('value[1]'), item | json_query('metric.instance')]] }}"
    loop: "{{ payload_requestscpu.json.data.result }}"

  - name: Assert that cpu requests compared to available cpu per node is below defined threshold
    assert:
      that: "{{ item[0] | int < openshift_upgrade_checks_requests_overall_cpu_query_threshold }}"
      quiet: yes
    loop: "{{ request_cpu_list }}"
    loop_control:
      label: "{{ item[1] }} < {{ openshift_upgrade_checks_requests_overall_cpu_query_threshold }}%"

- name: Verify that requests are actually consuming what they should consume
  block:
  - name: Retrieve requests cpu consumption against CPU requests
    uri:
      url:  "https://{{ role_prometheus_url[0] }}/api/v1/query?query={{ openshift_upgrade_checks_comsumption_overall_requests_query | urlencode }}"
      method: GET
      headers:
        Content-Type: application/json
        Accept: application/json
        Authorization: "Bearer {{ openshift_auth_results.openshift_auth.api_key }}"
      validate_certs: no
    register: payload_requestscpucons

  - name: Format request_cpu_cons usage data
    set_fact:
      request_cpucons_list: "{{ request_cpucons_list | default([]) + [[item | json_query('value[1]'), item | json_query('metric.instance')]] }}"
    loop: "{{ payload_requestscpucons.json.data.result }}"

  - name: Assert that cpu requests are actually consuming what they are reserving
    assert:
      that: "{{ item[0] | int < openshift_upgrade_checks_comsumption_overall_requests_query_threshold }}"
      quiet: yes
    loop: "{{ request_cpucons_list }}"
    loop_control:
      label: "{{ item[1] }} < {{ openshift_upgrade_checks_comsumption_overall_requests_query_threshold }}%"

- name: Verify that memory requests are below specified treshold
  block:
  - name: Retrieve requests memory  against total memory
    uri:
      url:  "https://{{ role_prometheus_url[0] }}/api/v1/query?query={{ openshift_upgrade_checks_requests_overall_mem_query | urlencode }}"
      method: GET
      headers:
        Content-Type: application/json
        Accept: application/json
        Authorization: "Bearer {{ openshift_auth_results.openshift_auth.api_key }}"
      validate_certs: no
    register: payload_requestsmem

  - name: Format request_mem_list usage data
    set_fact:
      request_mem_list: "{{ request_mem_list | default([]) + [[item | json_query('value[1]'), item | json_query('metric.instance')]] }}"
    loop: "{{ payload_requestsmem.json.data.result }}"

  - name: Assert that mem requests are below the defined treshold
    assert:
      that: "{{ item[0] | int < openshift_upgrade_checks_requests_overall_mem_query_threshold }}"
      quiet: yes
    loop: "{{ request_mem_list }}"
    loop_control:
      label: "{{ item[1] }} < {{ openshift_upgrade_checks_requests_overall_mem_query_threshold }}%"


